version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: talentsearchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - talent-network


  backend:
    image: karthikan123/talent-search-backend:latest
    container_name: backend

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/talentsearchdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123

    ports:
      - "9095:9095"

    networks:
      - talent-network


  frontend:
    image: karthikan123/talentsearch-frontend:latest
    container_name: frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - talent-network


volumes:
  postgres_data:

networks:
  talent-network:
